# Default values for contoso.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 2

image:
  repository:
  tag: latest
  pullPolicy: Always

settings:
  computeServiceAddress: "http://contoso:80/"
  appInsightsStorageFolder: "/tmp"
  adxClusterUrl: "https://myadxinstance.region.kusto.windows.net"
  adxDefaultDatabaseName: "myadxdatabase"
  aadClientId: "00000000-0000-0000-0000-000000000000"
  aadClientSecret: "secret/pa$$w0rd"
  aadTenantId: "00000000-0000-0000-0000-000000000000"
  instrumentationAppId: "contoso"
  instrumentationKey: "00000000-0000-0000-0000-000000000000"

service:
  type: ClusterIP
  port: 80
  targetPort: 80

ingress:
  enabled: false
  annotations: {}
