apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "contoso.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "contoso.name" . }}
    helm.sh/chart: {{ include "contoso.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "contoso.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "contoso.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          readinessProbe:
            httpGet:
              path: /health
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 20
          resources:
            requests:
              memory: "500Mi"
              cpu: "500m"
            limits:
              memory: "2000Mi"
              cpu: "2"
          envFrom:
          - configMapRef:
              name: {{ include "contoso.fullname" . }}-settings
          env:
            - name: aadClientSecret
              valueFrom:
                secretKeyRef:
                  name: {{ include "contoso.fullname" . }}-credentials
                  key: aadClientSecret
          volumeMounts:
            - name: appsettings-volume
              mountPath: /app/settings
      volumes:
        - name: appsettings-volume
          configMap:
            # Provide the name of the ConfigMap containing the files you want
            # to add to the container
            name: {{ include "contoso.fullname" . }}-appsettings
