# CI/CD Azure DevOps deployment pipeline.
# The following variables can be optionally set for each pipeline run:
# - RUN_FLAG_TERRAFORM: Set to 1 to have `terraform apply`. By default
#   `terraform apply` only runs on the master branch.
# - RUN_FLAG_PROMOTE: Set to 1 to promote the Docker image to `latest` tag if
#   tests are successful. By default this is only done on the master branch.
# - RUN_SET_NAMEBASE: Set to a string to deploy to the given AKS namespace,
#   and not delete the namespace after the build. By default the build deploys to
#   the `master` AKS namespace if run on the master branch, and otherwise to a
#   temporary AKS namespace that is deleted at the end of the build.

jobs:

- job: disk
  displayName: Build and unit tests
  pool: $(AGENT_POOL_NAME)
  steps:

  - bash: |
      pwd
      du -sm
      df -H

- job: disk
  displayName: Build and unit tests
  pool: $(AGENT_POOL_NAME)
  steps:

  - bash: |
      pwd
      du -sm
      df -H

- job: disk
  displayName: Build and unit tests
  pool: $(AGENT_POOL_NAME)
  steps:

  - bash: |
      pwd
      du -sm
      df -H

- job: disk
  displayName: Build and unit tests
  pool: $(AGENT_POOL_NAME)
  steps:

  - bash: |
      pwd
      du -sm
      df -H

